---
title: "12_strips"
output: html_document
---

```{r}
library(tidyverse)
#library(tidytuesdayR)
library(ggplot2)
library(ggtext)
library(RColorBrewer)


# this is a replica of : https://dominicroye.github.io/en/2018/how-to-create-warming-stripes-in-r/
```


```{r}

dat <- read_csv("https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/country_data/Romania.csv") %>% 
  data.frame()

dat <- dat %>% 
  mutate(daily_vaccinated = (people_vaccinated - lag(people_vaccinated, n = 1)),
         daily_vaccinations = (total_vaccinations - lag(total_vaccinations, n = 1)),
          month=substr(date,0,7))
dat$daily_vaccinated[is.na(dat$daily_vaccinated)] <- dat$people_vaccinated[1]
dat$daily_vaccinations [is.na(dat$daily_vaccinations )] <- dat$total_vaccinations[1]

```




```{r}
theme_strip <- theme_minimal()+
                 theme(plot.caption = element_markdown(size = 7, hjust=0.5, color="#252525"),
                       axis.text.y = element_blank(),
                       axis.line.y = element_blank(),
                       axis.title = element_blank(),
                       panel.grid.major = element_blank(),
                       legend.title = element_blank(),
                       axis.text.x = element_text(vjust = 3),
                       panel.grid.minor = element_blank(),
                       plot.title = element_text(size = 14, face = "bold"),
                       plot.margin = margin(6,4,4,4,"mm")
                       )


col_strip <- brewer.pal(11, "RdBu")

brewer.pal.info

dt<-dat %>% select(date, daily_vaccinations) 
    
ggplot(dt,
        aes(x = date, y = 1, fill = daily_vaccinations))+
        geom_tile()+
           scale_x_date(date_breaks = "7 days",
                     date_labels = "%m%d",
                     expand = c(0, 0))+
           scale_y_continuous(expand = c(0, 0))+
           scale_fill_gradientn(colors = rev(col_strip))+
             guides(fill = guide_colorbar(barwidth = 1))+
            labs(title="Romania's Daily Vaccinations",
                 subtitle="2020-present",
                caption = " #30DayChartChallenge | Day 12 Strips <br>Data Source: Our World in Data, April 2021",
              x="",
              y="") +
              theme_strip


ggsave("day12.png", height = 3.5, width = 7, dpi=300)

```

