---
title: "05_slope"
output: html_document
---

```{r}
library(tidyverse)
library(tidytuesdayR)
library(ggplot2)
library(ggtext)


```

```{r}
tuesdata <- tidytuesdayR::tt_load(2021, week = 9)
#employed <- tuesdata$employed
earned <- tuesdata$earn

df<-earned %>% 
  filter(year %in% c('2018','2019','2020'), sex=='Women') %>%
  filter(race=='All Races', ethnic_origin=='All Origins', age=='20 to 24 years') %>% 
  mutate(quarter=paste0("Q",quarter),
         date=paste0('Year ',year),
         pct=round(median_weekly_earn/lag(median_weekly_earn, n=4)*100,0)) %>% 
  filter(year %in% c('2019','2020')) %>% 
  select(date, quarter, pct) %>% 
  data.frame()

```



```{r}
ggplot(data = df, aes(x = date, y = pct, group=quarter) ) +
  geom_line(aes(color = quarter, alpha = 1), size = 2) +
  geom_point(aes(color = quarter, alpha = 1), size = 4) +
 theme_minimal() +
    theme(
    panel.grid.major.x = element_blank(),
    panel.border = element_blank(),
    axis.ticks.x = element_blank(),
    plot.title = element_markdown(face="bold",size = 13),
    plot.subtitle = element_markdown(size = 12),
    plot.caption = element_markdown(size = 7, hjust=0),
    axis.title.x = element_markdown(size = 7),
    axis.title.y = element_markdown(size = 7),
    axis.text.y = element_markdown(size = 6),
    legend.position="right",
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    plot.background = element_rect(fill = "#d8ebe4"),
    plot.margin = margin(5,3,4,4,"mm")
  )+
  labs(
    title = "Median weekly earn per quarter during 2019-2020",
    subtitle = " *Women aged 20-24 years* ",
    caption = " #30DayChartChallenge  <br> Day 5 Slope | Data Source: TidytuesdayR",
    x="",
    y=" Median Weekly Earnings YoY Index"
  )

 ggsave("day5.png", height = 3.5, width = 7, dpi=300)

```

