---
title: "13_correlation"
output: html_document
---

```{r}
library(tidyverse)
library(tidytuesdayR)
library(ggplot2)
library(ggtext)
library(RColorBrewer)
library(GGally)

tuesdata <- tidytuesdayR::tt_load(2021, week = 10)

youtube <- tuesdata$youtube

```


```{r}

my_theme<-theme(
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    plot.title = element_text(size = 13, hjust=0, color="#252525"), 
    plot.title.position = "plot",
    plot.subtitle = element_markdown(size = 11,hjust=0, color="#636363"),
    plot.caption = element_markdown(size = 7, hjust=0.5, color="#252525"),
    strip.text = element_text(face = "bold", color = "white",hjust = 0.5, size = 6),
    strip.background = element_rect(fill = "#636363", linetype = "solid", color="grey"),
    axis.text = element_markdown(),
    axis.title.x = element_markdown(),
    axis.title.y = element_markdown(),
    axis.text.x = element_blank(),
    axis.ticks.x=element_blank(),
    axis.ticks.y=element_blank(),
   # plot.background = element_rect(fill = "#fde0dd"),
    legend.position="none",
    plot.margin = margin(6,4,4,4,"mm")

  )

```


```{r}


my_data<-youtube %>% 
  mutate(date= lubridate::date(published_at) ) %>% 
  select(like_count, dislike_count, comment_count, view_count) %>% 
   mutate( across(ends_with("count"),
                  ~replace_na(.x, 0)) ) %>% 
  cor(use="p") %>% 
  data.frame() 

my_data$Var1 <- rownames(my_data)


```


```{r}

ggcorr(my_data, nbreaks=4, palette='RdGy', label=TRUE, label_size=6, label_color='white')+
  my_theme+
  labs(title="Likes, dislikes and comments",
        subtitle="on Youtube Ads",
        caption = " #30DayChartChallenge | Day 13 Correlation <br>Data Source: TidytuesdayR, 2021, week 10",
        x="",
        y="") 


ggsave("day13.png", height = 4.5, width = 9, dpi=150)

```

