---
title: "15_multivariate"
output: html_document
---

```{r}
library(tidyverse)
library(ggiraphExtra)
library(ggtext)

```


```{r}

my_theme<-theme(
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    plot.title = element_text(size = 13, hjust=0, color="#252525"), 
    plot.title.position = "plot",
    plot.subtitle = element_markdown(size = 11,hjust=0, color="#636363"),
    plot.caption = element_markdown(size = 7, hjust=0.5, color="#252525"),
    strip.text = element_text(face = "bold", color = "white",hjust = 0.5, size = 6),
    strip.background = element_rect(fill = "#636363", linetype = "solid", color="grey"),
    axis.text = element_markdown(),
    axis.title.x = element_markdown(),
    axis.title.y = element_markdown(),
    axis.text.x = element_blank(),
    axis.ticks.x=element_blank(),
    axis.ticks.y=element_blank(),
    #plot.background = element_rect(fill = "#fde0dd"),
    legend.position="right",
    plot.margin = margin(6,4,4,4,"mm")

  )

```



```{r}

ggBar(rose,
      aes(x=Month,fill=group,y=value),
      stat="identity",polar=TRUE,palette="Reds",width=1,
      color="black",size=0.1,interactive=FALSE) +
  my_theme +
  labs(title="Space Day",
       subtitle="",
      caption = " #30DayChartChallenge | Day 15 Multivariate <br>Data Source: sintetic ",
       x=" by group",
       y="temperature")


```


```{r}

ggsave("day15.png", height = 4.5, width = 9, dpi=150)

```

